# Generated by Django 4.2.1 on 2023-08-12 15:31

import acicweb.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardOfDirectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('designation', models.TextField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to=acicweb.models.getFileName)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Collabrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('government', models.TextField(max_length=1000)),
                ('corporate', models.TextField(max_length=1000)),
                ('academic', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityInnovativeSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=acicweb.models.getFileName)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MakersLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=acicweb.models.getFileName)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('designation', models.TextField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to=acicweb.models.getFileName)),
                ('international', models.BooleanField(default=False, help_text='0-default,1-international')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectorSpecificLab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=acicweb.models.getFileName)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StartUps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('designation', models.TextField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to=acicweb.models.getFileName)),
                ('head', models.BooleanField(default=False, help_text='0-default,1-head')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisObjCon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.TextField(max_length=1000)),
                ('objectives', models.TextField(max_length=2000)),
                ('contacts', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acicweb.events')),
            ],
        ),
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.TextField(max_length=500)),
                ('date', models.DateField(max_length=500)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=acicweb.models.getFileName)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=acicweb.models.getFileName)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=acicweb.models.getFileName)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=acicweb.models.getFileName)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=acicweb.models.getFileName)),
                ('image6', models.ImageField(blank=True, null=True, upload_to=acicweb.models.getFileName)),
                ('image7', models.ImageField(blank=True, null=True, upload_to=acicweb.models.getFileName)),
                ('image8', models.ImageField(blank=True, null=True, upload_to=acicweb.models.getFileName)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acicweb.events')),
                ('eventname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acicweb.eventnames')),
            ],
        ),
    ]
